# https://golangci-lint.run/usage/configuration/#config-file
version: "2"
exclusions: &common_exclusions
  generated: lax
  paths:
    - third_party$
    - builtin$
    - examples$

linters:
  enable:
    - errorlint
    - gosec
    - nilerr
    - nolintlint
  exclusions:
    <<: *common_exclusions
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions: *common_exclusions
