# https://golangci-lint.run/usage/configuration/#config-file
version: "2"
linters:
  enable:
    - errorlint
    - gosec
    - nilerr
    - nolintlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
