name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.golangci.yml'

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # for googleapis/release-please-action to create release commit
      pull-requests: write # for googleapis/release-please-action to create release PR
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CI_GITHUB_APP_ID }}
          private-key: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: main
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
